//
//  Conducting.swift
//  
//
//  Created by Dan Hart on 5/16/22.
//

import Foundation

/// Generated by SourceryPro
public protocol Conducting {
    // MARK: - Properties
    var apiKey: String? { get set }
    
    // MARK: - Functions
    func validate() async throws -> Bool
    func railStations() async throws -> [Station]
    func nextTrains(atStation code: String) async throws -> [Train]
}
